### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by nitinlkoin1984** [boundlessgeo/OSM#1]
Thanks for these style files. These really helped me.

I am planning to use the sld files in my project. Can I safely assume they have the same license as http://boundlessgeo.com/legal/opengeo-suite-eula/

Thanks
Nitin

**Comment by amillerBoundless** [comment]
My apologies, I just saw the question. Yes they have the same license as the OpenGeo Suite EULA

**Comment by nitinlkoin1984** [comment]
Thanks.
